# Generated by Django 4.1.7 on 2025-08-08 18:04

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('html_content', models.TextField()),
                ('css_content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SettingsGlobale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, null=True, upload_to='settings/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Логотип')),
                ('doplogo', models.FileField(blank=True, null=True, upload_to='settings/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Дополнительный логотип')),
                ('favicon', models.FileField(blank=True, null=True, upload_to='settings/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Фавикон')),
                ('paymentmetod', models.FileField(blank=True, null=True, upload_to='settings/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Методы оплаты')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название')),
                ('content', models.CharField(blank=True, max_length=500, null=True, verbose_name='Копирайт')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание')),
                ('message_header', models.TextField(blank=True, null=True, verbose_name='Шапка сообщения письма')),
                ('message_footer', models.TextField(blank=True, null=True, verbose_name='Подвал сообщения письма')),
                ('yandex_metrica', models.TextField(blank=True, null=True, verbose_name='Яндекс метрика')),
                ('google_analitic', models.TextField(blank=True, null=True, verbose_name='Гугл аналитика')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Сайты')),
                ('specialists', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Специалисты')),
            ],
            options={
                'verbose_name': 'Настройка сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('image', models.FileField(blank=True, default='default/imagegallery/imagegellery_images.png', null=True, upload_to='settings/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Изображение')),
                ('site', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='SettingsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('templates', models.CharField(default='site', max_length=500, verbose_name='Шаблон')),
                ('multilingual_enabled', models.BooleanField(default=False, verbose_name='Включить мультиязычность')),
                ('json_file', models.FileField(upload_to='templates_original/%Y/%m/%d/')),
                ('setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webmain.settingsglobale', verbose_name='Настройки')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Сайты')),
            ],
            options={
                'verbose_name': 'Настройка шаблона',
                'verbose_name_plural': 'Настройки шаблонов',
            },
        ),
        migrations.CreateModel(
            name='Seo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagetype', models.PositiveSmallIntegerField(choices=[(1, 'Главная страница'), (2, 'Новости'), (3, 'Каталог'), (4, 'Поиск'), (5, 'Покупки'), (6, 'Профиль'), (7, 'Закладки'), (8, 'Ресгистрации'), (9, 'Авторизация'), (10, 'Сбросить пароль'), (11, 'Партнерство'), (12, 'Сотрудничество'), (13, 'Контакты'), (14, 'ЧаВО'), (15, 'Специалисты'), (16, 'Поставщик социальных услуг')], default=1, unique=True, verbose_name='Странца')),
                ('previev', models.FileField(blank=True, default='default/imagegallery/imagegellery_images.png', null=True, upload_to='settings/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Превью')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Мета-заголовок')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание')),
                ('propertytitle', models.CharField(blank=True, max_length=150, null=True, verbose_name='Мета-заголовок ссылки')),
                ('propertydescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание ссылки')),
                ('setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webmain.settingsglobale', verbose_name='Настройки')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Сайты')),
            ],
            options={
                'verbose_name': 'Сео страницы',
                'verbose_name_plural': 'Сео страниц',
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagetype', models.PositiveSmallIntegerField(choices=[(1, 'Стандартная'), (2, 'Пользовательское соглашение'), (3, 'Политика конфедециальности'), (4, 'Политика Cookie - Файлов'), (5, 'Согласия на обработку персональных данных'), (6, 'Порядок предоставления услуг')], default=1, verbose_name='Тип')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('description', ckeditor.fields.RichTextField(db_index=True, verbose_name='Описание')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Мета-описание')),
                ('previev', models.FileField(blank=True, default='default/imagegallery/imagegellery_images.png', null=True, upload_to='settings/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Превью')),
                ('propertytitle', models.CharField(blank=True, max_length=150, null=True, verbose_name='Мета-заголовок ссылки')),
                ('propertydescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание ссылки')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Сайты')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('description', ckeditor.fields.RichTextField(db_index=True, verbose_name='Описание')),
                ('icon', models.FileField(blank=True, default='default/imagegallery/imagegellery_images.png', null=True, upload_to='settings/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Иконка')),
                ('longitude', models.CharField(max_length=250, verbose_name='Долгота')),
                ('width', models.CharField(max_length=250, verbose_name='Широта')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Мета-описание')),
                ('previev', models.FileField(blank=True, default='default/imagegallery/imagegellery_images.png', null=True, upload_to='settings/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Превью')),
                ('propertytitle', models.CharField(blank=True, max_length=150, null=True, verbose_name='Мета-заголовок ссылки')),
                ('propertydescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание ссылки')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Сайты')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('location', models.CharField(max_length=100, verbose_name='Местоположение')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('requirements', models.TextField(verbose_name='Требования')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Зарплата')),
                ('job_type', models.CharField(choices=[('full_time', 'Полная занятость'), ('part_time', 'Частичная занятость'), ('contract', 'Контракт'), ('internship', 'Стажировка')], max_length=20, verbose_name='Тип занятости')),
                ('experience_level', models.CharField(choices=[('entry', 'Начальный'), ('mid', 'Средний'), ('senior', 'Старший'), ('lead', 'Ведущий')], max_length=20, verbose_name='Уровень опыта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Мета-описание')),
                ('previev', models.FileField(blank=True, default='default/imagegallery/imagegellery_images.png', null=True, upload_to='settings/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Превью')),
                ('propertytitle', models.CharField(blank=True, max_length=150, null=True, verbose_name='Мета-заголовок ссылки')),
                ('propertydescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание ссылки')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Сайты')),
            ],
            options={
                'verbose_name': 'Вакансии',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Вопрос')),
                ('answer', models.TextField(blank=True, default=' ', null=True, verbose_name='Ответ')),
                ('create', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
                ('publishet', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('site', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='DocumentationsSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('file', models.FileField(upload_to='documentations/%Y/%m/%d/')),
                ('site', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Сайты')),
            ],
            options={
                'verbose_name': 'Документация',
                'verbose_name_plural': 'Документации',
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=150, null=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=150, null=True, verbose_name='Эл.Почта')),
                ('adress', models.CharField(blank=True, max_length=150, null=True, verbose_name='Адресс')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('telegram', models.CharField(blank=True, max_length=150, null=True, verbose_name='Телеграм')),
                ('whatsapp', models.CharField(blank=True, max_length=150, null=True, verbose_name='Вацап')),
                ('vk', models.CharField(blank=True, max_length=150, null=True, verbose_name='ВКонтакте')),
                ('grafik', models.CharField(blank=True, max_length=150, null=True, verbose_name='График')),
                ('setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webmain.settingsglobale', verbose_name='Настройки')),
                ('site', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Страница контакты',
                'verbose_name_plural': 'Страницы контакты',
            },
        ),
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Мета-описание')),
                ('cover', models.FileField(blank=True, null=True, upload_to='category/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Обложка категории')),
                ('icon', models.FileField(blank=True, null=True, upload_to='category/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Иконка категории')),
                ('image', models.FileField(blank=True, null=True, upload_to='category/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Картинка категории')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='webmain.categorys', verbose_name='Родитель')),
                ('site', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource', models.CharField(blank=True, max_length=550, null=True, verbose_name='Источник')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('description', ckeditor.fields.RichTextField(db_index=True, verbose_name='Описание')),
                ('previev', models.FileField(blank=True, default='default/imagegallery/imagegellery_images.png', null=True, upload_to='settings/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Превью')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Мета-описание')),
                ('propertytitle', models.CharField(blank=True, max_length=150, null=True, verbose_name='Мета-заголовок ссылки')),
                ('propertydescription', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мета-описание ссылки')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('cover', models.FileField(blank=True, default='default/blogs/cover.png', null=True, upload_to='blogs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Обложка')),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('create', models.DateTimeField(auto_now=True, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время')),
                ('pageviews', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество Просмотров')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Авторы')),
                ('category', models.ManyToManyField(blank=True, to='webmain.categorys', verbose_name='Категория')),
                ('site', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
