# Generated by Django 4.1.7 on 2025-08-08 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Оплата не прошла'), (2, 'Оплачено')], default=1, verbose_name='Статус')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('customer_surname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('customer_email', models.CharField(max_length=200, verbose_name='Адрес эл почты')),
                ('amount', models.PositiveSmallIntegerField(default=0, verbose_name='Сумма')),
                ('key', models.CharField(blank=True, max_length=32, unique=True, verbose_name='Ключ')),
                ('purchase_url', models.TextField(blank=True, null=True, verbose_name='Покупка юрл')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Яндекс'), (2, 'Тинькоф'), (3, 'Gateway'), (4, 'АльфаБанк')], default=1, verbose_name='Тип')),
                ('key_1', models.TextField(verbose_name='Первый ключ (public key)')),
                ('key_2', models.CharField(max_length=550, verbose_name='Второй ключ (secret key)')),
                ('shop_key', models.CharField(max_length=550, verbose_name='Ключ магазина (shop key)')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('turn_on', models.BooleanField(default=False, verbose_name='Включить')),
                ('image', models.FileField(blank=True, null=True, upload_to='payment_type/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'webp', 'jpeg', 'jpg', 'svg'])], verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
            },
        ),
    ]
