# Generated by Django 4.1.7 on 2025-08-08 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesquestion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='themes',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='themescourse', to='lms.course', verbose_name='Курсы'),
        ),
        migrations.AddField(
            model_name='themes',
            name='modules',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modulescourse', to='lms.modules', verbose_name='Модули'),
        ),
        migrations.AddField(
            model_name='streamsession',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_sessions', to='lms.themes'),
        ),
        migrations.AddField(
            model_name='schedulestream',
            name='themes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedulestreamsthemes', to='lms.themes', verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='schedulestream',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
        migrations.AddField(
            model_name='qwiz',
            name='themes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='lms.themes', verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='question',
            name='hints',
            field=models.ManyToManyField(blank=True, to='lms.hintstoquestion', verbose_name='Подсказки к вопросу'),
        ),
        migrations.AddField(
            model_name='question',
            name='qwiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_quiz', to='lms.qwiz', verbose_name='Задания'),
        ),
        migrations.AddField(
            model_name='modules',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.course', verbose_name='Курсы'),
        ),
        migrations.AddField(
            model_name='homeworkfiles',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_files', to='lms.homework', verbose_name='Домашнее задание'),
        ),
        migrations.AddField(
            model_name='homework',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='lms.themes'),
        ),
        migrations.AddField(
            model_name='homework',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='files',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes_file', to='lms.themes'),
        ),
        migrations.AddField(
            model_name='courseuser',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.course', verbose_name='Курсы'),
        ),
        migrations.AddField(
            model_name='courseuser',
            name='question',
            field=models.ManyToManyField(blank=True, to='lms.question', verbose_name='Варианты'),
        ),
        migrations.AddField(
            model_name='courseuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='coursesettings',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.course', verbose_name='Курсы'),
        ),
        migrations.AddField(
            model_name='coursesertificateuser',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.coursesertificate', verbose_name='Сертификат курса'),
        ),
        migrations.AddField(
            model_name='coursesertificateuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='coursesertificate',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='courserewievs',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='courserewievs',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='coursecomments',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='coursecomments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentcourse', to='lms.coursecomments', verbose_name='Родитель'),
        ),
        migrations.AddField(
            model_name='coursecomments',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='courseassistents',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Авторы'),
        ),
        migrations.AddField(
            model_name='courseassistents',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistentscourse', to='lms.course', verbose_name='Курсы'),
        ),
        migrations.AddField(
            model_name='course',
            name='assistants',
            field=models.ManyToManyField(blank=True, null=True, related_name='assistants', to=settings.AUTH_USER_MODEL, verbose_name='Помощники'),
        ),
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Авторы'),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ManyToManyField(blank=True, to='lms.categoryscourse', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='course',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='participants', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
        migrations.AddField(
            model_name='course',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.site', verbose_name='Сайт'),
        ),
        migrations.AddField(
            model_name='categoryscourse',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorycourse', to='lms.categoryscourse', verbose_name='Родитель'),
        ),
        migrations.AddField(
            model_name='assumptioncourse',
            name='needcourse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.needcourse', verbose_name='Нужен курс'),
        ),
        migrations.AddField(
            model_name='assumptioncourse',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
