# Generated by Django 4.1.7 on 2025-08-08 18:04

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Заявка'), (2, 'Покупка')], default=1, null=True, verbose_name='Тип')),
                ('email', models.CharField(blank=True, max_length=500, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=500, null=True, verbose_name='Телефон')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('create', models.DateTimeField(auto_now=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название компании')),
                ('company_inn', models.CharField(blank=True, max_length=500, null=True, verbose_name='ИНН организации или ИП')),
                ('company_director', models.CharField(blank=True, max_length=500, null=True, verbose_name='ФИО директора')),
                ('company_adress', models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес')),
                ('company_sku', models.CharField(blank=True, max_length=500, null=True, verbose_name='Количество товаров SKU в вашем каталоге')),
                ('company_description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='DocumentationsModer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('type', models.SmallIntegerField(choices=[(0, 'Для модераторов'), (1, 'Для пользователей'), (2, 'Для преподавателей')], default=1, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Документация',
                'verbose_name_plural': 'Документации',
            },
        ),
        migrations.CreateModel(
            name='DocumentationsModerMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documentations/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Файл документации',
                'verbose_name_plural': 'Файлы документации',
            },
        ),
        migrations.CreateModel(
            name='ModerationGroups',
            fields=[
                ('type_option', models.PositiveSmallIntegerField(choices=[(1, 'Общяя'), (2, 'Внутреняя')], default=1, verbose_name='Тип')),
                ('types', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Пользователи'), (2, 'Добавление пользователя'), (3, 'Удаления пользователя'), (4, 'Редактирование пользователя'), (5, 'Блокирование пользователя'), (6, 'Разблокировка пользователя'), (7, 'Группы'), (8, 'Добавление групп'), (9, 'Удаления/Редактирование групп'), (10, 'Добавление должностей'), (11, 'Заявки на рассмотрение'), (12, 'Обработка заявки на рассмотрение'), (13, 'Заявки на обратную связь'), (14, 'Обработка заявки на обратную связь'), (15, 'Задачи'), (16, 'Добавление задачи'), (17, 'Удаление задачи'), (18, 'Редактирование задачи'), (19, 'Записи'), (20, 'Добавление записи'), (21, 'Удаление записи'), (22, 'Редактирование паспортных данных в задаче'), (23, 'Добавление подзадачи'), (24, 'Удаление подзадачи'), (25, 'Редактирование подзадачи'), (26, 'Общие настройки сайта'), (27, 'Страницы'), (28, 'Добавление страницы'), (29, 'Удаление страницы'), (30, 'Редактирование страницы'), (31, 'Новости'), (32, 'Добавление новости'), (33, 'Удаление новости'), (34, 'Редактирование новости'), (35, 'ЧаВо'), (36, 'Добавление ЧаВо'), (37, 'Удаление ЧаВо'), (38, 'Редактирование ЧаВо'), (39, 'Галерея'), (40, 'Добавление галереи'), (41, 'Удаление галереи'), (42, 'Редактирование галереи'), (43, 'Тарифы'), (44, 'Добавление тарифа'), (45, 'Удаление тарифа'), (46, 'Редактирование тарифа'), (47, 'СЕО'), (48, 'Добавление СЕО'), (49, 'Удаление СЕО'), (50, 'Редактирование СЕО'), (51, 'Товары'), (52, 'Импорт'), (53, 'Склады'), (54, 'Добавление складов'), (55, 'Удаление складов'), (56, 'Редактирование складов'), (57, 'Контакты'), (58, 'Добавление контактов'), (59, 'Удаление контактов'), (60, 'Редактирование контактов'), (61, 'Бухгалтерия'), (62, 'Языки'), (63, 'Инструкция'), (64, 'Профиль'), (65, 'Проделанная работа'), (66, 'Личный график'), (67, 'Звонки'), (68, 'Мессенджеры')], default=[], max_length=255, verbose_name='Доступ')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.TextField(editable=False)),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.SmallIntegerField(choices=[(0, 'Новое'), (1, 'Обратная связь'), (2, 'В процессе'), (3, 'Решенный'), (4, 'Закрытый')], default=0, verbose_name='Статус')),
                ('themas', models.TextField(verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Тикет',
                'verbose_name_plural': 'Тикеты',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'Заказчик'), (1, 'Поддержка')], default=1, editable=False, verbose_name='Статус')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('content', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Комментарий тикета',
                'verbose_name_plural': 'Комментарии тикета',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TicketCommentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ticket/%Y/%m/%d/tiket_file/')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='moderation.ticketcomment')),
            ],
            options={
                'verbose_name': 'Файл комментария тикета',
                'verbose_name_plural': 'Файлы комментариев тикета',
            },
        ),
    ]
