# Generated by Django 4.1.7 on 2025-08-08 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videochatuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_room', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='videochatroom',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='videochatroom',
            name='notadded',
            field=models.ManyToManyField(blank=True, related_name='notadded', to='conference.videochatuser', verbose_name='не добавленные'),
        ),
        migrations.AddField(
            model_name='videochatroom',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to='conference.videochatuser', verbose_name='Участники'),
        ),
        migrations.AddField(
            model_name='videochatroom',
            name='primary',
            field=models.ManyToManyField(blank=True, related_name='primary', to='conference.videochatuser', verbose_name='Основной экран'),
        ),
        migrations.AddField(
            model_name='videochatroom',
            name='spiker',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='spiker', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AddField(
            model_name='videochatroom',
            name='visitors',
            field=models.ManyToManyField(blank=True, related_name='visitors', to='conference.videochatuser', verbose_name='Посетители'),
        ),
        migrations.AddField(
            model_name='videochatmessages',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_messages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='videochatmessages',
            name='videoroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videoroom_messages', to='conference.videochatroom', verbose_name='Видеочат'),
        ),
        migrations.AddField(
            model_name='videochatfile',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_files', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='videochatfile',
            name='videoroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videoroom_files', to='conference.videochatroom', verbose_name='Видеочат'),
        ),
        migrations.AddField(
            model_name='signal',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='conference.videochatroom'),
        ),
        migrations.AddField(
            model_name='signal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='conference.videochatuser'),
        ),
    ]
