from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(CourseSettings)
admin.site.register(Course)
admin.site.register(Needcourse)
admin.site.register(Assumptioncourse)
admin.site.register(Schedulestream)
admin.site.register(Themes)
admin.site.register(Qwiz)
admin.site.register(Question)
admin.site.register(Coursesertificate)
admin.site.register(Courseuser)
admin.site.register(Coursesertificateuser)
admin.site.register(Coursecomments)
admin.site.register(Courserewievs)
admin.site.register(CategorysCourse)
admin.site.register(Modules)
admin.site.register(Files)
admin.site.register(CourseAssistents)
admin.site.register(ThemesQuestion)
admin.site.register(HomeWorkFiles)
admin.site.register(HomeWork)
admin.site.register(HintsToQuestion)